version: "3.8"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  grafana:
    image: "grafana/grafana"
    ports:
      - "8080:3000"
  prometheus:
    image: "prom/prometheus"
    ports:
      - "8081:9090"